### ISSUE TITLE
Confusing remark about reading ReadAtIndex from AppliedIndex

### ISSUE THREAD

**Issue by hermanbanken** [Jille/raft-grpc-example#1]
First of all, I really like this very concrete example! Really helps to get a head start.

See remark:
https://github.com/Jille/raft-grpc-example/blob/f5868cdacef4bcbd7f7d83d1a76b2d7fc2dd5012/application.go#L96

The comment from AppliedIndex specifically mentions that it can lag behind the application state. How would one implement the TODO locking? I have no idea.

It would be really great if you could share your insights.

**Comment by Jille** [comment]
Glad to hear it :)

It should simply be a mutex to prevent both Apply() and other goroutines from touching the shared state in wordTracker. I've resolved the TODO.

Does that clarify it?

**Comment by hermanbanken** [comment]
I think my main uncertainty was from not knowing how/when the Raft implementation will call the Apply of the FSM when the Apply of raft.Raft is called.

If that is a direct call in the same routine then indeed a Mutex is easy.

**Comment by Jille** [comment]
Followers definitely run Apply() in some background thread.

Note that (*raft.Raft).Apply() will return before (*wordTracker).Apply() is done. Only once ApplyFuture.Error() has returned you'll know it's done.

**Comment by hermanbanken** [comment]
The confusion was from the fact that the TODO was in a function on `rpcInterface`, which wraps both Raft and wordTracker. And both Raft and wordTracker have a method called `Apply`.

Having a mutex within wordTracker is logical and easy, but I was struggling to understand how to mutex writes at Raft.Apply + workTracker reads. Maybe the comment was just a bit misplaced.

The new code shows it very clearly 👍
