### ISSUE TITLE
unknown field Scheme in struct literal of type resolver.Target

### ISSUE THREAD

**Issue by bye430** [Jille/raft-grpc-example#3]
I followed the steps in README and run
_go install github.com/Jille/raftadmin/cmd/raftadmin@latest_
then I met this error:_
# github.com/Jille/grpc-multi-resolver
/go/pkg/mod/github.com/!jille/grpc-multi-resolver@v1.2.0/target.go:19:3: unknown field Scheme in struct literal of type resolver.Target
/go/pkg/mod/github.com/!jille/grpc-multi-resolver@v1.2.0/target.go:20:3: unknown field Authority in struct literal of type resolver.Target_

**Comment by mahditakrim** [comment]
> I followed the steps in README and run _go install github.com/Jille/raftadmin/cmd/raftadmin@latest_ then I met this error:_
> 
> # github.com/Jille/grpc-multi-resolver
> /go/pkg/mod/github.com/!jille/grpc-multi-resolver@v1.2.0/target.go:19:3: unknown field Scheme in struct literal of type resolver.Target /go/pkg/mod/github.com/!jille/grpc-multi-resolver@v1.2.0/target.go:20:3: unknown field Authority in struct literal of type resolver.Target_

This repository has not been updated for a substantial period of time. In addition, HashiCorp's implementation of the Raft consensus algorithm leaves room for improvement in some areas. Therefore, I am considering building my own implementation of the algorithm from the ground up, in order to fully comprehend the concepts and potentially produce a more robust solution :)

**Comment by Jille** [comment]
gRPC keeps making backwards incompatible changes. If you can downgrade your grpc to v1.55.0 it'll work. I'll upgrade grpc-multi-resolver in a few days. (Feel free to poke me if I didn't yet)

**Comment by Jille** [comment]
I just pushed version 1.3.0 to https://github.com/Jille/grpc-multi-resolver which works for gRPC v1.57 and above.

**Comment by Jille** [comment]
Closing this as fixed :)
